<?xml version="1.0" encoding="utf-8"?><Database Name="MCALDB" Class="MDKDbContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\;Initial Catalog=MCALDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MCALDBConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.getAcademicDetails" Method="getAcademicDetails">
    <ElementType Name="getAcademicDetailsResult">
      <Column Name="StudentRoll" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Math" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Chemistry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Physics" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getAllStudentInfo" Method="getAllStudentInfo">
    <ElementType Name="getAllStudentInfoResult">
      <Column Name="StudentRoll" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Math" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Chemistry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Physics" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getPersonalDetails" Method="getPersonalDetails">
    <ElementType Name="getPersonalDetailsResult">
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.procColumnConfig" Method="procColumnConfig">
    <ElementType Name="procColumnConfigResult">
      <Column Name="ColumnName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ColumnType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Group]" Member="Group" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.procColumnConfigAcademicDetails" Method="procColumnConfigAcademicDetails">
    <ElementType Name="procColumnConfigAcademicDetailsResult">
      <Column Name="ColumnName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ColumnType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Group]" Member="Group" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.procColumnConfigPersonalDetails" Method="procColumnConfigPersonalDetails">
    <ElementType Name="procColumnConfigPersonalDetailsResult">
      <Column Name="ColumnName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ColumnType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Group]" Member="Group" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>