#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicColumnGrid
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MCALDB")]
	public partial class MDKDbContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MDKDbContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MCALDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MDKDbContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MDKDbContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MDKDbContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MDKDbContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAcademicDetails")]
		public ISingleResult<getAcademicDetailsResult> getAcademicDetails()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getAcademicDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAllStudentInfo")]
		public ISingleResult<getAllStudentInfoResult> getAllStudentInfo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getAllStudentInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getPersonalDetails")]
		public ISingleResult<getPersonalDetailsResult> getPersonalDetails()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getPersonalDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procColumnConfig")]
		public ISingleResult<procColumnConfigResult> procColumnConfig()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<procColumnConfigResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procColumnConfigAcademicDetails")]
		public ISingleResult<procColumnConfigAcademicDetailsResult> procColumnConfigAcademicDetails()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<procColumnConfigAcademicDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procColumnConfigPersonalDetails")]
		public ISingleResult<procColumnConfigPersonalDetailsResult> procColumnConfigPersonalDetails()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<procColumnConfigPersonalDetailsResult>)(result.ReturnValue));
		}
	}
	
	public partial class getAcademicDetailsResult
	{
		
		private string _StudentRoll;
		
		private string _StudentName;
		
		private System.Nullable<int> _Math;
		
		private System.Nullable<int> _Chemistry;
		
		private System.Nullable<int> _Physics;
		
		public getAcademicDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentRoll", DbType="NVarChar(50)")]
		public string StudentRoll
		{
			get
			{
				return this._StudentRoll;
			}
			set
			{
				if ((this._StudentRoll != value))
				{
					this._StudentRoll = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentName", DbType="NVarChar(50)")]
		public string StudentName
		{
			get
			{
				return this._StudentName;
			}
			set
			{
				if ((this._StudentName != value))
				{
					this._StudentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Math", DbType="Int")]
		public System.Nullable<int> Math
		{
			get
			{
				return this._Math;
			}
			set
			{
				if ((this._Math != value))
				{
					this._Math = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chemistry", DbType="Int")]
		public System.Nullable<int> Chemistry
		{
			get
			{
				return this._Chemistry;
			}
			set
			{
				if ((this._Chemistry != value))
				{
					this._Chemistry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Physics", DbType="Int")]
		public System.Nullable<int> Physics
		{
			get
			{
				return this._Physics;
			}
			set
			{
				if ((this._Physics != value))
				{
					this._Physics = value;
				}
			}
		}
	}
	
	public partial class getAllStudentInfoResult
	{
		
		private string _StudentRoll;
		
		private string _StudentName;
		
		private System.Nullable<int> _Math;
		
		private System.Nullable<int> _Chemistry;
		
		private System.Nullable<int> _Physics;
		
		private string _ContactNumber;
		
		private string _EmailId;
		
		private string _Address;
		
		public getAllStudentInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentRoll", DbType="NVarChar(50)")]
		public string StudentRoll
		{
			get
			{
				return this._StudentRoll;
			}
			set
			{
				if ((this._StudentRoll != value))
				{
					this._StudentRoll = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentName", DbType="NVarChar(50)")]
		public string StudentName
		{
			get
			{
				return this._StudentName;
			}
			set
			{
				if ((this._StudentName != value))
				{
					this._StudentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Math", DbType="Int")]
		public System.Nullable<int> Math
		{
			get
			{
				return this._Math;
			}
			set
			{
				if ((this._Math != value))
				{
					this._Math = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chemistry", DbType="Int")]
		public System.Nullable<int> Chemistry
		{
			get
			{
				return this._Chemistry;
			}
			set
			{
				if ((this._Chemistry != value))
				{
					this._Chemistry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Physics", DbType="Int")]
		public System.Nullable<int> Physics
		{
			get
			{
				return this._Physics;
			}
			set
			{
				if ((this._Physics != value))
				{
					this._Physics = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="NVarChar(50)")]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this._ContactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="NVarChar(50)")]
		public string EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this._EmailId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(250)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
	}
	
	public partial class getPersonalDetailsResult
	{
		
		private string _StudentName;
		
		private string _ContactNumber;
		
		private string _EmailId;
		
		private string _Address;
		
		public getPersonalDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentName", DbType="NVarChar(50)")]
		public string StudentName
		{
			get
			{
				return this._StudentName;
			}
			set
			{
				if ((this._StudentName != value))
				{
					this._StudentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="NVarChar(50)")]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this._ContactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="NVarChar(50)")]
		public string EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this._EmailId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(250)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
	}
	
	public partial class procColumnConfigResult
	{
		
		private string _ColumnName;
		
		private string _ColumnType;
		
		private string _Group;
		
		public procColumnConfigResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnName", DbType="NVarChar(50)")]
		public string ColumnName
		{
			get
			{
				return this._ColumnName;
			}
			set
			{
				if ((this._ColumnName != value))
				{
					this._ColumnName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnType", DbType="NVarChar(50)")]
		public string ColumnType
		{
			get
			{
				return this._ColumnType;
			}
			set
			{
				if ((this._ColumnType != value))
				{
					this._ColumnType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group]", Storage="_Group", DbType="NVarChar(50)")]
		public string Group
		{
			get
			{
				return this._Group;
			}
			set
			{
				if ((this._Group != value))
				{
					this._Group = value;
				}
			}
		}
	}
	
	public partial class procColumnConfigAcademicDetailsResult
	{
		
		private string _ColumnName;
		
		private string _ColumnType;
		
		private string _Group;
		
		public procColumnConfigAcademicDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnName", DbType="NVarChar(50)")]
		public string ColumnName
		{
			get
			{
				return this._ColumnName;
			}
			set
			{
				if ((this._ColumnName != value))
				{
					this._ColumnName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnType", DbType="NVarChar(50)")]
		public string ColumnType
		{
			get
			{
				return this._ColumnType;
			}
			set
			{
				if ((this._ColumnType != value))
				{
					this._ColumnType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group]", Storage="_Group", DbType="NVarChar(50)")]
		public string Group
		{
			get
			{
				return this._Group;
			}
			set
			{
				if ((this._Group != value))
				{
					this._Group = value;
				}
			}
		}
	}
	
	public partial class procColumnConfigPersonalDetailsResult
	{
		
		private string _ColumnName;
		
		private string _ColumnType;
		
		private string _Group;
		
		public procColumnConfigPersonalDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnName", DbType="NVarChar(50)")]
		public string ColumnName
		{
			get
			{
				return this._ColumnName;
			}
			set
			{
				if ((this._ColumnName != value))
				{
					this._ColumnName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnType", DbType="NVarChar(50)")]
		public string ColumnType
		{
			get
			{
				return this._ColumnType;
			}
			set
			{
				if ((this._ColumnType != value))
				{
					this._ColumnType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group]", Storage="_Group", DbType="NVarChar(50)")]
		public string Group
		{
			get
			{
				return this._Group;
			}
			set
			{
				if ((this._Group != value))
				{
					this._Group = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
